# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016-2019 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.


notifications:
  email: false

sudo: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"

  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

  - "requirements-builder --level=min --extras userprofiles setup.py > .travis-lowest-requirements-with-profiles.txt"
  - "requirements-builder --level=pypi --extras userprofiles setup.py > .travis-release-requirements-with-profiles.txt"
  - "requirements-builder --level=dev --extras userprofiles --req requirements-devel.txt setup.py > .travis-devel-requirements-with-profiles.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[docs,tests]"

script:
  # test without userprofiles
  - "./run-tests.sh"
  # test again with userprofiles
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements-with-profiles.txt"
  - "travis_retry pip install -e .[all]"
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: nharraud
  password:
    secure: "0CgIMFnEd7imBlCgNWR+ZVKnpOwCBmo9hXLZV4LiVl+kdMPrgr0y9JytH3i4GWz/lgoEQ7iUMtNxC4R3U76y/jdKF4JryHaeabX1KJcYB+sIuBonk07txE09TmNPyoHsTNt9BIQ9K8faaFWWZufxa3yBbrN7Mcxro1EGVrP1La10JwVF9zmeUWba0DC4PIk4rIQmVDQOGdPWRNrj6NnuPRYS4ss+sXxN5GkCJeulqVehQn98kPuKFM3R7mpOxuoERIAlrpnESw3xXfQCRmzB9ubza1n3G1jz+IOBEPQt2XbJABCwGAIy4rci00yIpHVhbYxVhCFaBLlpgVjuE6uc6p5q5TxRxlipcUc71rsiC3bxzP3spEUPUfmKix9GrHJadvMrKb5ueyurnXqwgqSwRZJeOrw8M5hFGIjRjK/UvyOYcDVRk2vxHPvKnXPiC7SsUEvhk9CvffWoww+ZbZTofLEwNf12F8N4rnCqZ3qjXS6/enOk0vmDWYNTMqeb//+vheoP3WpXpo6KPdKq5T9zisSWGAK69+ouHd5cYOr1CuuyyolVtt8ewP0pjvXDziUiqUDq+sD/As5fIVvxllpsBk6Zjb3EjtwFizzeRi/8L59rl3ogqIAOCA7yQ4XOwRZvwU3+37eo+buFsIvvHrnonzYN4C5KoU7mRIwRNGAAVnM="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
